// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/vida-plus/api/models"
)

// JWTManager is an autogenerated mock type for the JWTManager type
type JWTManager struct {
	mock.Mock
}

type JWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTManager) EXPECT() *JWTManager_Expecter {
	return &JWTManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *JWTManager) Generate(user *models.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*models.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type JWTManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user *models.User
func (_e *JWTManager_Expecter) Generate(user interface{}) *JWTManager_Generate_Call {
	return &JWTManager_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *JWTManager_Generate_Call) Run(run func(user *models.User)) *JWTManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *JWTManager_Generate_Call) Return(_a0 string, _a1 error) *JWTManager_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManager_Generate_Call) RunAndReturn(run func(*models.User) (string, error)) *JWTManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: token
func (_m *JWTManager) Validate(token string) (*models.AuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *models.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.AuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.AuthClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type JWTManager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *JWTManager_Expecter) Validate(token interface{}) *JWTManager_Validate_Call {
	return &JWTManager_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *JWTManager_Validate_Call) Run(run func(token string)) *JWTManager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *JWTManager_Validate_Call) Return(_a0 *models.AuthClaims, _a1 error) *JWTManager_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManager_Validate_Call) RunAndReturn(run func(string) (*models.AuthClaims, error)) *JWTManager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTManager creates a new instance of JWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTManager {
	mock := &JWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
