// Code generated by mockery v2.53.4. DO NOT EDIT.

package domain

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vida-plus/api/internal/domain"
)

// JWTManagerMock is an autogenerated mock type for the JWTManager type
type JWTManagerMock struct {
	mock.Mock
}

type JWTManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTManagerMock) EXPECT() *JWTManagerMock_Expecter {
	return &JWTManagerMock_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *JWTManagerMock) Generate(user *domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManagerMock_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type JWTManagerMock_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user *domain.User
func (_e *JWTManagerMock_Expecter) Generate(user interface{}) *JWTManagerMock_Generate_Call {
	return &JWTManagerMock_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *JWTManagerMock_Generate_Call) Run(run func(user *domain.User)) *JWTManagerMock_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *JWTManagerMock_Generate_Call) Return(_a0 string, _a1 error) *JWTManagerMock_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManagerMock_Generate_Call) RunAndReturn(run func(*domain.User) (string, error)) *JWTManagerMock_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function with given fields: user
func (_m *JWTManagerMock) GenerateRefreshToken(user *domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManagerMock_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type JWTManagerMock_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - user *domain.User
func (_e *JWTManagerMock_Expecter) GenerateRefreshToken(user interface{}) *JWTManagerMock_GenerateRefreshToken_Call {
	return &JWTManagerMock_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", user)}
}

func (_c *JWTManagerMock_GenerateRefreshToken_Call) Run(run func(user *domain.User)) *JWTManagerMock_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *JWTManagerMock_GenerateRefreshToken_Call) Return(_a0 string, _a1 error) *JWTManagerMock_GenerateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManagerMock_GenerateRefreshToken_Call) RunAndReturn(run func(*domain.User) (string, error)) *JWTManagerMock_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: token
func (_m *JWTManagerMock) Validate(token string) (*domain.AuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManagerMock_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type JWTManagerMock_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *JWTManagerMock_Expecter) Validate(token interface{}) *JWTManagerMock_Validate_Call {
	return &JWTManagerMock_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *JWTManagerMock_Validate_Call) Run(run func(token string)) *JWTManagerMock_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *JWTManagerMock_Validate_Call) Return(_a0 *domain.AuthClaims, _a1 error) *JWTManagerMock_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManagerMock_Validate_Call) RunAndReturn(run func(string) (*domain.AuthClaims, error)) *JWTManagerMock_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: token
func (_m *JWTManagerMock) ValidateRefreshToken(token string) (*domain.AuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTManagerMock_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type JWTManagerMock_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *JWTManagerMock_Expecter) ValidateRefreshToken(token interface{}) *JWTManagerMock_ValidateRefreshToken_Call {
	return &JWTManagerMock_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *JWTManagerMock_ValidateRefreshToken_Call) Run(run func(token string)) *JWTManagerMock_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *JWTManagerMock_ValidateRefreshToken_Call) Return(_a0 *domain.AuthClaims, _a1 error) *JWTManagerMock_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTManagerMock_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*domain.AuthClaims, error)) *JWTManagerMock_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTManagerMock creates a new instance of JWTManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTManagerMock {
	mock := &JWTManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
