// Code generated by mockery v2.53.4. DO NOT EDIT.

package models

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vida-plus/api/models"
)

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

type UserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStore) EXPECT() *UserStore_Expecter {
	return &UserStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserStore) Create(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *UserStore_Expecter) Create(ctx interface{}, user interface{}) *UserStore_Create_Call {
	return &UserStore_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserStore_Create_Call) Run(run func(ctx context.Context, user *models.User)) *UserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *UserStore_Create_Call) Return(_a0 error) *UserStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStore_Create_Call) RunAndReturn(run func(context.Context, *models.User) error) *UserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserStore) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStore_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserStore_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserStore_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserStore_GetByEmail_Call {
	return &UserStore_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserStore_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserStore_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStore_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *UserStore_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStore_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *UserStore_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserStore) GetByID(ctx context.Context, id string) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserStore_Expecter) GetByID(ctx interface{}, id interface{}) *UserStore_GetByID_Call {
	return &UserStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStore_GetByID_Call) Return(_a0 *models.User, _a1 error) *UserStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStore_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *UserStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserStore creates a new instance of UserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStore {
	mock := &UserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
