// Code generated by mockery v2.53.4. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vida-plus/api/internal/domain"
)

// UserStoreMock is an autogenerated mock type for the UserStore type
type UserStoreMock struct {
	mock.Mock
}

type UserStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStoreMock) EXPECT() *UserStoreMock_Expecter {
	return &UserStoreMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserStoreMock) Create(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStoreMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserStoreMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *UserStoreMock_Expecter) Create(ctx interface{}, user interface{}) *UserStoreMock_Create_Call {
	return &UserStoreMock_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserStoreMock_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *UserStoreMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *UserStoreMock_Create_Call) Return(_a0 error) *UserStoreMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStoreMock_Create_Call) RunAndReturn(run func(context.Context, *domain.User) error) *UserStoreMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserStoreMock) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStoreMock_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserStoreMock_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserStoreMock_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserStoreMock_GetByEmail_Call {
	return &UserStoreMock_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserStoreMock_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserStoreMock_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStoreMock_GetByEmail_Call) Return(_a0 *domain.User, _a1 error) *UserStoreMock_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStoreMock_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserStoreMock_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserStoreMock) GetByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStoreMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserStoreMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserStoreMock_Expecter) GetByID(ctx interface{}, id interface{}) *UserStoreMock_GetByID_Call {
	return &UserStoreMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserStoreMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserStoreMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStoreMock_GetByID_Call) Return(_a0 *domain.User, _a1 error) *UserStoreMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStoreMock_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserStoreMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserStoreMock creates a new instance of UserStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStoreMock {
	mock := &UserStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
