# mockery configuration for Vida Plus API
all: false
with-expecter: true

packages:
  github.com/vida-plus/api/internal/domain:
    config:
      all: true
      dir: "mocks"
      filename: "{{ .InterfaceName | snakecase }}_mocks.go"
      mockname: "{{ .InterfaceName }}Mock"
